### ISSUE TITLE
So file missing

### ISSUE THREAD

**Issue by kmshiori** [AdColony/AdColony-Android-SDK-3#1] opened 2016-10-13 08:47 UTC
I had tried to use Gradle & Manually, but i get the same error result

> E/AdColony [ERROR]: Expecting libadcolony.so in libs directory but it was not found.

Version 3.0.4

**Comment by mwhite-ac** [comment] 2016-10-13 10:40
__________________________________
Please type your reply at the top of the email...

------------------------------------------------------

 

 



Melissa White | OCT 13, 2016 03:40AM PDT




Thank you for getting in touch with us.

Please send a full console log showing all app activity from when you initialize our SDK through this error so that we can see how our SDK and your code are interacting.  Please also let me know what version of the Android OS you are building for and testing on.

When you reply, make sure that you copy support@adcolony.com so that your response will be transferred to your support ticket.

Best,
Melissa



_____________________________
Melissa White
Head of Technical Support
melissa.white@adcolony.com  |  http://adcolony.com/





------------------------------------------------------




 





kmshiori | OCT 13, 2016 03:35AM PDT  | Original message 

  




---------- Forwarded message ----------

**Comment by Philio** [comment] 2016-10-13 11:24
Same problem

    E/AdColony [ERROR]: Expecting libadcolony.so in libs directory but it was not found.

Then when trying to play and ad:

    E/AdColony [ERROR]: The AdColony API is not available while AdColony is disabled.

Tried both gradle and copying the jar/so files into libs.

**Comment by Philio** [comment] 2016-10-13 12:05
Solved the problem by clearing every cache possible...

Removed:

~/.gradle/
project/.gradle
project/app/build

Also did invalidate caches/restart and disabled instant run as a precaution.

**Comment by mwhite-ac** [comment] 2016-10-13 17:37
__________________________________
Please type your reply at the top of the email...

------------------------------------------------------

 

 



Andrew Kong | OCT 13, 2016 10:36AM PDT




Hi kmshiori,

Could you try clearing the gradle cache like what Philio did to solve his problem here? We added some .so files for more architectures (arm64-v8a and x86_64) just yesterday, which could have caused the issue you are seeing:
https://github.com/AdColony/AdColony-Android-SDK-3/issues/1#issuecomment-253494541

Thanks,
Andrew









------------------------------------------------------




 



Melissa White | OCT 13, 2016 03:40AM PDT




Thank you for getting in touch with us.

Please send a full console log showing all app activity from when you initialize our SDK through this error so that we can see how our SDK and your code are interacting.  Please also let me know what version of the Android OS you are building for and testing on.

When you reply, make sure that you copy support@adcolony.com so that your response will be transferred to your support ticket.

Best,
Melissa



_____________________________
Melissa White
Head of Technical Support
melissa.white@adcolony.com  |  http://adcolony.com/





------------------------------------------------------




 





kmshiori | OCT 13, 2016 03:35AM PDT  | Original message 

  




---------- Forwarded message ----------

**Comment by Philio** [comment] 2016-10-13 17:47
I think that's what happened to me and why your demo worked but my app didn't.
I first added 3.0.4 a few days ago, but actually my phone is arm64 v8 I think (Nexus 6P/Snapdragon 810) but downloaded the demo this morning so wasn't an issue.

I don't think Gradle will actively look to update a dependency where the version is already stored locally (unless it's a snapshot) so anyone else who proactively switched to your Gradle build (thanks for providing this btw, it's a much better option) and is trying to test on one of the architectures just added may be running into this issue. Bumping your version number next time would avoid it.

P.S. Your emails display rather badly in the Github UI

**Comment by akwkong** [comment] 2016-10-13 19:25
Thank you for posting about the steps you took to fix the issue on your end, Phil. It does sound like the problem is occurring because of the new .so files we added yesterday.

For anyone else running into the same issue, try clearing your Gradle cache by deleting the ~/.gradle/caches folder. If that does not fix the issue by itself, try following the steps that Phil laid out in his comment.

Yes, we will have to look into how to get our email replies to display better in GitHub. If you happen to know of a good way, please let us know!

**Closed by akwkong** 2016-10-13 19:25 UTC

**Comment by mwhite-ac** [comment] 2016-10-17 22:08
@Philio 
Thanks for letting us know about the display issues with the emails coming from our ticket system!
